// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skbmjksoaehlqjkjlzaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrYm1qa3NvYWVobHFqa2psemFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjUyNTYsImV4cCI6MjA3MTEwMTI1Nn0.LN1S7G85KZqM_tmaGB_0oCMnz6z0r0cyBdxzz461LM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});